export type ListType = {
  id: number;
  label: string;
  country: string;
};

export const CountryList: Array<ListType> = [
  { id: 1, label: "USA", country: "USA" },
  { id: 2, label: "Canada", country: "Canada" },
];

export const StateList: Array<ListType> = [
  { id: 1, label: "AL", country: "USA" },
  { id: 2, label: "AK", country: "USA" },
  { id: 3, label: "AZ", country: "USA" },
  { id: 4, label: "AR", country: "USA" },
  { id: 5, label: "CA", country: "USA" },
  { id: 6, label: "CO", country: "USA" },
  { id: 7, label: "CT", country: "USA" },
  { id: 8, label: "DE", country: "USA" },
  { id: 9, label: "FL", country: "USA" },
  { id: 10, label: "GA", country: "USA" },
  { id: 11, label: "HI", country: "USA" },
  { id: 12, label: "ID", country: "USA" },
  { id: 13, label: "IL", country: "USA" },
  { id: 14, label: "IN", country: "USA" },
  { id: 15, label: "IA", country: "USA" },
  { id: 16, label: "KS", country: "USA" },
  { id: 17, label: "KY", country: "USA" },
  { id: 18, label: "LA", country: "USA" },
  { id: 19, label: "ME", country: "USA" },
  { id: 20, label: "MD", country: "USA" },
  { id: 21, label: "MA", country: "USA" },
  { id: 22, label: "MI", country: "USA" },
  { id: 23, label: "MN", country: "USA" },
  { id: 24, label: "MS", country: "USA" },
  { id: 25, label: "MO", country: "USA" },
  { id: 26, label: "MT", country: "USA" },
  { id: 27, label: "NE", country: "USA" },
  { id: 28, label: "NV", country: "USA" },
  { id: 29, label: "NH", country: "USA" },
  { id: 30, label: "NJ", country: "USA" },
  { id: 31, label: "NM", country: "USA" },
  { id: 32, label: "NY", country: "USA" },
  { id: 33, label: "NC", country: "USA" },
  { id: 34, label: "ND", country: "USA" },
  { id: 35, label: "OH", country: "USA" },
  { id: 36, label: "OK", country: "USA" },
  { id: 37, label: "OR", country: "USA" },
  { id: 38, label: "PA", country: "USA" },
  { id: 39, label: "RI", country: "USA" },
  { id: 40, label: "SC", country: "USA" },
  { id: 41, label: "SD", country: "USA" },
  { id: 42, label: "TN", country: "USA" },
  { id: 43, label: "TX", country: "USA" },
  { id: 44, label: "UT", country: "USA" },
  { id: 45, label: "VT", country: "USA" },
  { id: 46, label: "VA", country: "USA" },
  { id: 47, label: "WA", country: "USA" },
  { id: 48, label: "WV", country: "USA" },
  { id: 49, label: "WI", country: "USA" },
  { id: 50, label: "WY", country: "USA" },
  { id: 51, label: "ON", country: "Canada" },
  { id: 52, label: "QC", country: "Canada" },
  { id: 53, label: "NS", country: "Canada" },
  { id: 54, label: "NB", country: "Canada" },
  { id: 55, label: "MB", country: "Canada" },
  { id: 56, label: "BC", country: "Canada" },
  { id: 57, label: "PE", country: "Canada" },
  { id: 58, label: "SK", country: "Canada" },
  { id: 59, label: "AB", country: "Canada" },
  { id: 60, label: "NL", country: "Canada" },
  { id: 61, label: "NT", country: "Canada" },
  { id: 62, label: "YT", country: "Canada" },
  { id: 63, label: "NU", country: "Canada" },
];
